services:
  shelter-postgres:
    image: postgres:latest
    volumes:
      - shelter-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  client:
    build: ./client
    image: shelter-client
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    build: ./server
    image: shelter-server
    ports:
      - 8080:8080
    depends_on:
      - shelter-postgres

volumes:
  shelter-data: